["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "realms marketplace"

["protostar.contracts"]
marketplace = [
    "./contracts/nft_marketplace/bibliotheca_marketplace.cairo",
]
