["protostar.config"]
protostar_version = "0.2.0"

["protostar.project"]
libs_path = "./lib"

# This section is explained in the "Project compilation" guide.
["protostar.contracts"]
main = [
  "./src/main.cairo",
]